# Funding (Caracal Open Source)
# Funding supports the development and sustainability of Caracal Open Source.

# Sponsorship does not grant ownership, governance rights, roadmap influence, feature guarantees, commercial privileges, or support obligations unless explicitly agreed to by the CODEOWNERS (.github/CODEOWNERS).
# Sponsors may be acknowledged publicly as supporters of the project. Any commitments beyond public sponsorship recognition are made solely at the discretion of the CODEOWNERS and must be communicated separately.

# For commercial, enterprise, or partnership inquiries:
# * CEO, Garudex Labs: rawx18.dev@gmail.com
# * Team Caracal: contact@caracal.run
# * Website: https://caracal.run

github: RAWx18
