"""
Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
Caracal, a product of Garudex Labs

Lynx Capital Control API provisioning script.
"""
from __future__ import annotations

import json
import os
import secrets
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import tenancy
from control_client import (
    ControlClient,
    ControlError,
    config_from_env,
    find_by_identifier,
    find_by_name,
)

ROOT = Path(__file__).resolve().parent.parent
OUTPUTS_PATH = ROOT / "config" / "provisioned.json"
APPLICATION_ENV_PATH = ROOT / "config" / "provisioned.env"


def _id_of(result: object) -> str:
    if not isinstance(result, dict) or not result.get("id"):
        raise ControlError(f"control response missing id: {result!r}")
    return str(result["id"])


def _version_id(result: object) -> str:
    if isinstance(result, dict):
        direct = result.get("version_id")
        if direct:
            return str(direct)
        version = result.get("version")
        if isinstance(version, dict) and version.get("id"):
            return str(version["id"])
        if not isinstance(version, dict) and result.get("id"):
            return str(result["id"])
    raise ControlError(f"control response missing version_id: {result!r}")


def _existing_secrets() -> dict[str, str]:
    """Client secrets already captured in config/provisioned.env, keyed by env key, so an
    idempotent re-run preserves working credentials instead of rotating them needlessly."""
    secrets_by_key: dict[str, str] = {}
    if not APPLICATION_ENV_PATH.exists():
        return secrets_by_key
    for line in APPLICATION_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        if name.startswith("LYNX_CARACAL_") and name.endswith("_CLIENT_SECRET") and value:
            secrets_by_key[name[len("LYNX_CARACAL_"):-len("_CLIENT_SECRET")]] = value
    return secrets_by_key


def _rotation_opt_in() -> bool:
    """Whether the operator has explicitly authorized rotating the client secret of an
    application that already exists but whose secret is not known locally."""
    return os.environ.get("LYNX_PROVISION_ALLOW_SECRET_ROTATION", "").strip().lower() in (
        "1", "true", "yes", "on",
    )


def _guard_secret_rotation(
    model: tenancy.TenancyModel, existing: object, known_secrets: dict[str, str]
) -> None:
    """Fail before touching any state when provisioning would rotate the live secret of an
    application that already exists but is not represented in config/provisioned.env.
    Rotating it would invalidate the credential every other running workload holds, so it
    must be an explicit, opted-in action rather than a silent side effect of a routine run."""
    if _rotation_opt_in():
        return
    at_risk = [
        app.applicationName
        for app in model.applications
        if find_by_name(existing, app.applicationName)
        and app.id.upper().replace("-", "_") not in known_secrets
    ]
    if at_risk:
        raise ControlError(
            "refusing to rotate client secrets for existing applications whose secrets are "
            f"not in config/provisioned.env: {', '.join(at_risk)}. Rotating them would break "
            "every other workload holding the current secret. Restore the existing secrets "
            "into config/provisioned.env, or set LYNX_PROVISION_ALLOW_SECRET_ROTATION=1 to "
            "explicitly rotate them (this invalidates all other holders)."
        )


def ensure_applications(client: ControlClient, model: tenancy.TenancyModel) -> dict[str, str]:
    """Create each managed application boundary and persist a working client secret for the
    local workload environment file. New applications capture their one-time secret; existing
    applications reuse a secret already captured here. An existing application whose secret is
    not known locally is never rotated silently — rotation invalidates the credential every
    other running workload holds, so it must be opted into explicitly."""
    existing = client.invoke("app", "list")
    known_secrets = _existing_secrets()
    _guard_secret_rotation(model, existing, known_secrets)
    application_ids: dict[str, str] = {}
    fd = os.open(APPLICATION_ENV_PATH, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    os.fchmod(fd, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as application_env:
        application_env.write(
            "# Generated by scripts/provision.py. Loaded automatically by the workload at\n"
            "# startup (app/main.py); no manual merge into .env is required.\n\n"
        )
        for app in model.applications:
            found = find_by_name(existing, app.applicationName)
            result = found if found else client.invoke("app", "create", {"name": app.applicationName})
            application_ids[app.id] = _id_of(result)
            env_key = app.id.upper().replace("-", "_")
            if not found and isinstance(result, dict) and result.get("client_secret"):
                secret = str(result["client_secret"])
                disposition = "created"
            elif env_key in known_secrets:
                secret = known_secrets[env_key]
                disposition = "reused"
            else:
                secret = secrets.token_urlsafe(32)
                client.invoke("app", "patch", {"id": application_ids[app.id], "client-secret": secret})
                disposition = "rotated"
            print(f"application {'exists' if found else 'created'} ({disposition} secret): {app.applicationName}")
            application_env.write(f"LYNX_CARACAL_{env_key}_APPLICATION_ID={application_ids[app.id]}\n")
            application_env.write(f"LYNX_CARACAL_{env_key}_CLIENT_SECRET={secret}\n\n")
            print(f"  export LYNX_CARACAL_{env_key}_APPLICATION_ID={application_ids[app.id]}")
    print(f"wrote {APPLICATION_ENV_PATH.relative_to(ROOT)}")
    return application_ids


def ensure_providers(client: ControlClient, model: tenancy.TenancyModel) -> dict[str, str]:
    """Register each upstream credential provider, returning a map of provider identifier to
    the control-plane id so resources can bind to it. Existing providers are patched so
    config changes (endpoints, credentials, token host allowlists) reconcile on re-run."""
    existing = client.invoke("identity-provider", "list")
    provider_ids: dict[str, str] = {}
    for command in tenancy.provider_commands(model):
        identifier = command["flags"]["identifier"]
        found = find_by_identifier(existing, identifier)
        if found:
            client.invoke("identity-provider", "patch", {
                "id": _id_of(found),
                "kind": command["flags"]["kind"],
                "config": command["flags"]["config"],
            })
            result = found
            print(f"provider patched: {identifier}")
        else:
            result = client.run(command)
            print(f"provider created: {identifier}")
        provider_ids[identifier] = _id_of(result)
    return provider_ids


def ensure_resources(
    client: ControlClient,
    model: tenancy.TenancyModel,
    provider_ids: dict[str, str],
    application_ids: dict[str, str],
) -> None:
    """Create each per-application resource view. Existing views are patched so upstream
    URLs, scopes, and bindings reconcile on re-run."""
    existing = client.invoke("resource", "list")
    for command in tenancy.resource_commands(model, provider_ids, application_ids):
        identifier = command["flags"]["identifier"]
        found = find_by_identifier(existing, identifier)
        if found:
            client.invoke("resource", "patch", {
                "id": _id_of(found),
                "scopes": command["flags"]["scopes"],
                "upstream-url": command["flags"]["upstream-url"],
                "credential-provider-id": command["flags"]["credential-provider-id"],
                "gateway-application-id": command["flags"]["gateway-application-id"],
            })
            print(f"resource patched: {identifier}")
            continue
        client.run(command)
        print(f"resource created: {identifier}")


def ensure_policy_set(client: ControlClient, model: tenancy.TenancyModel, application_ids: dict[str, str]) -> None:
    """Author the policy library with the bindings and grants documents rendered from the
    live application ids and tenancy plan, then version and activate the policy set."""
    overrides = {
        "01-bindings": tenancy.render_bindings_rego(application_ids),
        "02-grants": tenancy.render_grants_rego(model),
    }
    existing_policies = client.invoke("policy", "list")
    version_ids: list[str] = []
    for command in tenancy.policy_commands(model, overrides=overrides):
        name = command["flags"]["name"]
        found = find_by_name(existing_policies, name)
        if found:
            result = client.invoke("policy", "version", {
                "id": found["id"],
                "content": command["flags"]["content"],
                "schema-version": command["flags"]["schema-version"],
            })
            print(f"policy versioned: {name}")
        else:
            result = client.run(command)
            print(f"policy created: {name}")
        version_ids.append(_version_id(result))

    set_name = model.policySet.name
    existing_set = find_by_name(client.invoke("policy-set", "list"), set_name)
    if existing_set:
        set_id = existing_set.get("id")
        print(f"policy-set exists: {set_name}")
    else:
        created = client.invoke("policy-set", "create", {
            "name": set_name,
            "description": model.policySet.description,
        })
        set_id = _id_of(created)
        print(f"policy-set created: {set_name}")

    if not version_ids:
        print("policy-set: no policy version ids returned; author versions and activate in Console")
        return
    version = client.invoke("policy-set", "version", {
        "id": set_id,
        "policy-versions": ",".join(version_ids),
    })
    set_version_id = _version_id(version)
    client.invoke("policy-set", "activate", {"id": set_id, "version": set_version_id})
    print(f"policy-set activated: {set_name} ({set_version_id})")


def write_outputs(
    application_ids: dict[str, str],
    provider_ids: dict[str, str],
    model: tenancy.TenancyModel,
) -> None:
    outputs = {
        "applications": {
            a.id: {"name": a.applicationName, "application_id": application_ids.get(a.id, "")}
            for a in model.applications
        },
        "providers": provider_ids,
        "resources": [r.identifier for r in model.resources],
        "policy_set": model.policySet.name,
    }
    OUTPUTS_PATH.write_text(json.dumps(outputs, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUTS_PATH.relative_to(ROOT)}")


def main() -> None:
    model = tenancy.load_model()
    client = ControlClient(config_from_env())
    application_ids = ensure_applications(client, model)
    provider_ids = ensure_providers(client, model)
    ensure_resources(client, model, provider_ids, application_ids)
    ensure_policy_set(client, model, application_ids)
    write_outputs(application_ids, provider_ids, model)
    terms = json.dumps(tenancy.partnership_manifest(model), separators=(",", ":"))
    print("partnership terms for the mandate-verifying providers (export before starting the provider lab):")
    print(f"  export LYNX_CARACAL_PARTNERSHIP='{terms}'")
    print(
        f"provisioned {len(model.applications)} applications, {len(model.providers)} providers, "
        f"{len(model.resources)} resource views, and the {model.policySet.name} policy set"
    )


if __name__ == "__main__":
    main()
