#!/usr/bin/env node
// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Writes apps/cli/src/runtime/version.gen.ts with the dev-stamped CLI identity and prints the short SHA on stdout.

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const cliRoot = resolve(here, '..')
const repoRoot = resolve(cliRoot, '..', '..')

function baseVersion() {
  const raw = readFileSync(resolve(cliRoot, 'runtime/release.json'), 'utf8')
  return JSON.parse(raw).version
}

function shortSha() {
  if (process.env.CARACAL_DEV_SHA) return process.env.CARACAL_DEV_SHA
  try {
    return execSync('git rev-parse --short HEAD', { cwd: repoRoot }).toString().trim()
  } catch {
    return 'nogit'
  }
}

const sha = shortSha()
const version = `${baseVersion()}+dev.${sha}`

const body =
  `// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped CLI identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_VERSION = '${version}'
export const CARACAL_MODE: 'dev' | 'runtime' = 'dev'
`

writeFileSync(resolve(cliRoot, 'src/runtime/version.gen.ts'), body, 'utf8')
process.stdout.write(`${sha}\n`)
