// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped Console identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_CONSOLE_VERSION = '2026.05.14-dev.sha256a668a'
export const CARACAL_CONSOLE_MODE: 'dev' | 'rc' | 'stable' = 'dev'
export const CARACAL_CONSOLE_SHA = '256a668a'
