// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped Console identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_CONSOLE_VERSION = '2026.05.26-rc.1'
export const CARACAL_CONSOLE_MODE: 'dev' | 'rc' | 'stable' = 'rc'
export const CARACAL_CONSOLE_SHA = '6fb19ecb'
