# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import treasury_pb2 as treasury__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in treasury_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TreasuryOpsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCashPosition = channel.unary_unary(
                '/lynx.treasury.TreasuryOps/GetCashPosition',
                request_serializer=treasury__pb2.CashPositionRequest.SerializeToString,
                response_deserializer=treasury__pb2.CashPositionResponse.FromString,
                _registered_method=True)
        self.ForecastLiquidity = channel.unary_unary(
                '/lynx.treasury.TreasuryOps/ForecastLiquidity',
                request_serializer=treasury__pb2.ForecastRequest.SerializeToString,
                response_deserializer=treasury__pb2.ForecastResponse.FromString,
                _registered_method=True)
        self.PlaceFxHedge = channel.unary_unary(
                '/lynx.treasury.TreasuryOps/PlaceFxHedge',
                request_serializer=treasury__pb2.FxHedgeRequest.SerializeToString,
                response_deserializer=treasury__pb2.FxHedgeResponse.FromString,
                _registered_method=True)
        self.TransferFunds = channel.unary_unary(
                '/lynx.treasury.TreasuryOps/TransferFunds',
                request_serializer=treasury__pb2.TransferRequest.SerializeToString,
                response_deserializer=treasury__pb2.TransferResponse.FromString,
                _registered_method=True)


class TreasuryOpsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCashPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForecastLiquidity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceFxHedge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreasuryOpsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCashPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCashPosition,
                    request_deserializer=treasury__pb2.CashPositionRequest.FromString,
                    response_serializer=treasury__pb2.CashPositionResponse.SerializeToString,
            ),
            'ForecastLiquidity': grpc.unary_unary_rpc_method_handler(
                    servicer.ForecastLiquidity,
                    request_deserializer=treasury__pb2.ForecastRequest.FromString,
                    response_serializer=treasury__pb2.ForecastResponse.SerializeToString,
            ),
            'PlaceFxHedge': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceFxHedge,
                    request_deserializer=treasury__pb2.FxHedgeRequest.FromString,
                    response_serializer=treasury__pb2.FxHedgeResponse.SerializeToString,
            ),
            'TransferFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFunds,
                    request_deserializer=treasury__pb2.TransferRequest.FromString,
                    response_serializer=treasury__pb2.TransferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lynx.treasury.TreasuryOps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lynx.treasury.TreasuryOps', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TreasuryOps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCashPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lynx.treasury.TreasuryOps/GetCashPosition',
            treasury__pb2.CashPositionRequest.SerializeToString,
            treasury__pb2.CashPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForecastLiquidity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lynx.treasury.TreasuryOps/ForecastLiquidity',
            treasury__pb2.ForecastRequest.SerializeToString,
            treasury__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceFxHedge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lynx.treasury.TreasuryOps/PlaceFxHedge',
            treasury__pb2.FxHedgeRequest.SerializeToString,
            treasury__pb2.FxHedgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lynx.treasury.TreasuryOps/TransferFunds',
            treasury__pb2.TransferRequest.SerializeToString,
            treasury__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
