# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: treasury.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'treasury.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etreasury.proto\x12\rlynx.treasury\"(\n\x13\x43\x61shPositionRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\"$\n\x14\x43\x61shPositionResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\":\n\x0f\x46orecastRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x14\n\x0chorizon_days\x18\x02 \x01(\x05\" \n\x10\x46orecastResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\"?\n\x0e\x46xHedgeRequest\x12\x0c\n\x04pair\x18\x01 \x01(\t\x12\x10\n\x08notional\x18\x02 \x01(\x01\x12\r\n\x05tenor\x18\x03 \x01(\t\"\x1f\n\x0f\x46xHedgeResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\"v\n\x0fTransferRequest\x12\x14\n\x0c\x66rom_account\x18\x01 \x01(\t\x12\x12\n\nto_account\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\" \n\x10TransferResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2\xe0\x02\n\x0bTreasuryOps\x12Z\n\x0fGetCashPosition\x12\".lynx.treasury.CashPositionRequest\x1a#.lynx.treasury.CashPositionResponse\x12T\n\x11\x46orecastLiquidity\x12\x1e.lynx.treasury.ForecastRequest\x1a\x1f.lynx.treasury.ForecastResponse\x12M\n\x0cPlaceFxHedge\x12\x1d.lynx.treasury.FxHedgeRequest\x1a\x1e.lynx.treasury.FxHedgeResponse\x12P\n\rTransferFunds\x12\x1e.lynx.treasury.TransferRequest\x1a\x1f.lynx.treasury.TransferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'treasury_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CASHPOSITIONREQUEST']._serialized_start=33
  _globals['_CASHPOSITIONREQUEST']._serialized_end=73
  _globals['_CASHPOSITIONRESPONSE']._serialized_start=75
  _globals['_CASHPOSITIONRESPONSE']._serialized_end=111
  _globals['_FORECASTREQUEST']._serialized_start=113
  _globals['_FORECASTREQUEST']._serialized_end=171
  _globals['_FORECASTRESPONSE']._serialized_start=173
  _globals['_FORECASTRESPONSE']._serialized_end=205
  _globals['_FXHEDGEREQUEST']._serialized_start=207
  _globals['_FXHEDGEREQUEST']._serialized_end=270
  _globals['_FXHEDGERESPONSE']._serialized_start=272
  _globals['_FXHEDGERESPONSE']._serialized_end=303
  _globals['_TRANSFERREQUEST']._serialized_start=305
  _globals['_TRANSFERREQUEST']._serialized_end=423
  _globals['_TRANSFERRESPONSE']._serialized_start=425
  _globals['_TRANSFERRESPONSE']._serialized_end=457
  _globals['_TREASURYOPS']._serialized_start=460
  _globals['_TREASURYOPS']._serialized_end=812
# @@protoc_insertion_point(module_scope)
