// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped TUI identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_TUI_VERSION = '2026.05.14'
export const CARACAL_TUI_MODE: 'dev' | 'runtime' = 'dev'
