#!/usr/bin/env node
// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Writes apps/tui/src/version.gen.ts with the dev-stamped TUI identity.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const tuiRoot = resolve(here, '..')
const repoRoot = resolve(tuiRoot, '..', '..')

function baseVersion() {
  const raw = readFileSync(resolve(repoRoot, 'packages/engine/runtime/release.json'), 'utf8')
  return JSON.parse(raw).version
}

const version = process.env.CARACAL_RELEASE_VERSION ?? baseVersion()

const body =
  `// Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
// Caracal, a product of Garudex Labs
//
// Stamped TUI identity. Generated by scripts/stampDev.mjs in dev or scripts/stampRelease.mjs in CI.

export const CARACAL_TUI_VERSION = '${version}'
export const CARACAL_TUI_MODE: 'dev' | 'runtime' = 'dev'
`

writeFileSync(resolve(tuiRoot, 'src/version.gen.ts'), body, 'utf8')
